### ISSUE TITLE
Get details of an app broken

### ISSUE THREAD

**Issue by mrtnkzr** [kodie/serverpilot-shell#2]
Hi!

When retrieving info of an app the info is not displayed correctly.

`[root@private admin]# serverpilot apps LHtfC4x4I4SMzlkacj
datecreated         sysuserid           runtime             id                  autossl             name                serverid
1472809266          pG7ksUL3ngKQxrfzkN    php7.0              LHtfC4x4I4SMzlkacj    {                   "available":        false               }                   testiser            66vVcNcpQl02qCcOHs            `

With multiple domains:

`[root@private admin]# serverpilot apps L9ccxpIPjAfMUc0jv
datecreated         sysuserid           runtime             id                  autossl             name                serverid
1484480068          taBJdxhSDfLOWVbvJZ    php7.0              L9ccxpIPjAfMUc0jv    {                   "available":        true,               "domains":          [                   "www.testdomain.com","cdn.testdomain.com","cdn1.testdomain.com","cdn2.testdomain.com","testdomain.com",   "cdn3.testdomain.com"]                   }                   testuser          Wzisq7j9kvxMexlzX  `

Is this a problem in the serverpilot shell script?

Thanks,
Maarten

**Comment by kodie** [comment]
Thanks for letting me know! I'll look into it. Thanks!

**Comment by kodie** [comment]
Fixed!
