### ISSUE TITLE
Create WordPress app fails

### ISSUE THREAD

**Issue by mrtnkzr** [kodie/serverpilot-shell#3]
Hi,

When using the create app function as shown in the example gallery it all works as expected. But the WordPress installation is not working:

`[root@private admin]# serverpilot apps create wordpress fqtjBhKFDaVoYUWAL php7.0 '["example.com","www.example.com"]' '{"site_title":"My WordPress Site","admin_user":"admin","admin_password":"mypassword","admin_email":"maarten@keizer.it"}'
Error: Invalid JSON request: {"name":"wordpress","sysuserid":"fqtjBhKFDaVoYUWAL","runtime":"php7.0","domains":["example.com","www.example.com"],"wordpress":{"site_title":"My} `

How should this work? That's like the main reason to use serverpilot-shell for me :)

Thanks,
Maarten

**Comment by kodie** [comment]
Will look into it! Thanks!

**Comment by kodie** [comment]
Fixed!
