### ISSUE TITLE
Rows of data bleed into each other and columns are random...

### ISSUE THREAD

**Issue by thewzrd** [kodie/serverpilot-shell#4]
Sometimes an app label is so long that it bleeds into another row, such that when you're pulling that data apart with bash you end up having the serverID appended to an app name, for example. The problem is exacerbated by the fact that it seems like the columns themselves can vary from one system to another (on machine A the order of the details about all the apps might be: php appid appname serverid sysuserid datecreated and on machine B the order is sysuserid php serverid datecreated appname appid). So I'm wondering how to make each column "wider" I guess to solve the first problem. And then I'm curious if there is a way to make sure that the column presentation itself was consistent from one machine to the next. I'm not any good with any programming languages, I'm trying to work through this all with just bash which I'm not expert at either. Thanks so much for all your hard work - forgive my ignorance.

**Comment by kodie** [comment]
Thanks for letting me know about this @thewzrd, I'll look into it!

**Comment by thewzrd** [comment]
So an update on this, after lots of extensive additional testing, my findings are...

If you provision a bunch of new Ubuntu 16.04 servers (all my tests have been on this) you'll consistently see the problem of columns shifting around. And there's no visible rhyme or reason - they don't seem to shift in any discernable pattern. 

And the only column that can really spill out too long is the name of the app. All of the column lengths, in terms of the output that your code creates, are the same. But if an app name is too long it can spill into the next column. Which makes the whole thing get more complicated. 

If you build logic into your bash to look for the columns or prompt the user for what column is what then you can obviously work around it.

But it continues to make it difficult to really automate things with bash and your API wrapper. 

Final note: I thought at first that the problem was an incorrect installation/build or jq, but that's not it. I've tried a clean install on three machines in a row and I get different orders of the columns for each. 

Hope this helps.

**Comment by thewzrd** [comment]
Looks like I've at least found a temporary workaround for me, maybe...

The app names I'm having trouble with are 20 characters long or more, so by changing this:

> printf "%-20s"

to this

> printf "%-30s"

with this...

> sed -i 's/printf "%-20s"/printf "%-30s"/g' /usr/local/bin/serverpilot

Voila. Fixes the problem of columns bleeding into each other.

But it obviously doesn't tackle the "random order of columns" problem.
